This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./Main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Main.acn....done (137 entries accepted, 0 rejected).
Sorting entries....done (1054 comparisons).
Generating output file Main.acr....done (53 lines written, 0 warnings).
Output written in Main.acr.
Transcript written in Main.alg.
